### ISSUE TITLE
créer une fiche détection (revue design)

### ISSUE THREAD

**Issue by CoralieCotonPro** [betagouv/seves#177]
Objet de l'événement : 
- le champ date n'est pas calé 

![Image](https://github.com/user-attachments/assets/c97563b4-1198-4e8c-94b1-c32f933acd21)

Lieu : 
- je ne peux pas cochr la case "etablissement" donc pas entrer les infos
- lien base adresse ?

Prélèvement 
- ajouter un prélèvement / espèce de l'échantilon : on n'a pas les données ?
- n° phytopass : on ne fait pas de controle de format ?
- date de prélèvement : controle de cohérence avec date de 1 er signalement ?
- date de prélèvement : le champ n'est pas calé 
- je dois pouvoir ajouter le résultat du prelevement

perf : au clic sur publier j'ai eu un loading très très très long / pareil pour la modification enregistrement

![Image](https://github.com/user-attachments/assets/0d8eaae9-6a02-4ca9-8b1e-c78c1b8a3d3f)

```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/seves/issues/54
- [ ] https://github.com/betagouv/seves/issues/170
- [ ] https://github.com/betagouv/seves/issues/62
- [ ] https://github.com/betagouv/seves/issues/37
- [ ] https://github.com/betagouv/seves/issues/204
- [ ] https://github.com/betagouv/seves/issues/210
```

**Comment by alanzirek** [comment]
@CoralieCotonPro 

Pour les points suivants, j'ai ajouté les issues (cf. liste Tasks dans [1er commentaire](https://github.com/betagouv/seves/issues/177#issue-2413993900))

> * le champ date n'est pas calé
> * date de prélèvement : le champ n'est pas calé
> * je ne peux pas cochr la case "etablissement" donc pas entrer les infos
> * lien base adresse ?
> * ajouter un prélèvement / espèce de l'échantilon : on n'a pas les données ?
> * je dois pouvoir ajouter le résultat du prelevement
> * perf : au clic sur publier j'ai eu un loading très très très long / pareil pour la modification enregistrement

Pour le reste, voir commentaire sous chaque point.
> * n° phytopass : on ne fait pas de controle de format ?

Non car peut contenir des lettres aussi donc c'est stocké en chaîne de caractères.

> * date de prélèvement : controle de cohérence avec date de 1 er signalement ?

Je ne sais pas, il faut demander au métier. Doit-on ajouter la contrainte ?
