### ISSUE TITLE
États d'une fiche détection

### ISSUE THREAD

**Issue by alanzirek** [betagouv/seves#3]
## Spécifications
https://www.notion.so/betagouv-dinum/tats-d-une-fiche-d-tection-36534a093fe54ac7bbce9e5565a4d4de?pvs=4

## Design
_lien figma_

```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/seves/issues/57
- [ ] https://github.com/betagouv/seves/issues/59
- [ ] https://github.com/betagouv/seves/issues/258
- [ ] https://github.com/betagouv/seves/issues/261
```
