### ISSUE TITLE
Plusieurs modèles n'ont pas de contraintes d'unicité

### ISSUE THREAD

**Issue by Anto59290** [betagouv/seves#330]
Par exemple le nom n'est pas unique sur les modèles de Labo, on peut avoir deux laboratoire qui ont exactement le même nom.
```[tasklist]
### Tasks
- [x] OrganismeNuisible: code_oepp + libelle_court
- [x] StatutReglementaire: code + libelle
- [x] Contexte: nom
- [x] StatutEtablissement: libelle
- [x] PositionChaineDistribution: libelle
- [x] StructurePreleveur: nom
- [x] SiteInspection: nom
- [x] MatricePrelevee: libelle
- [x] EspeceEchantillon: code_oepp + libelle
- [x] LaboratoireAgree: nom
- [x] LaboratoireConfirmationOfficielle: nom
- [x] StatutEvenement: libelle
```

**Comment by alanzirek** [comment]
@Anto59290 j'ai listé les champs et modèles ou il me semble que la contrainte soit nécessaire
