### ISSUE TITLE
Attribution automatique de l'état `en cours` après une certaine période

### ISSUE THREAD

**Issue by alanzirek** [betagouv/seves#59]
## Notes
Utilisation du service [Scalingo Scheduler](https://doc.scalingo.com/platform/app/task-scheduling/scalingo-scheduler) pour gérer le statut `en cours` attribué automatiquement après une certaine période (cf. spec.)

```[tasklist]
### Tasks
- [x] Créer une commande Django `update_fiche_status` pour passer l'état `nouveau` à `en cours`
- [x] Planifier la commande sur Scalingo (cf. fichier `cron.json`)
- [x] Gérer les risques d'exécution manquée (cf. [doc Scalingo](https://doc.scalingo.com/platform/app/task-scheduling/scalingo-scheduler)) -> exécuter le script plus fréquemment que nécessaire (par exemple, deux fois par jour au lieu d'une seule)
- [x] Mise en place monitoring ([Healthchecks](https://healthchecks.io/) ou [Sentry](https://docs.sentry.io/product/crons/)) pour avertir si la tâche planifiée n'a pas été exécutée comme prévu
```
